"""Metabolism -- the thermodynamic substrate.

This replaces symbolic resource *accounting* with a small dynamical system of
three coupled state variables, so cognitive behaviour becomes a consequence of
constrained physics rather than of bookkeeping:

    Energy   -- a *conserved* capacity to do work.  It does not appear from
                nowhere: it is drawn from a shared :class:`EnergyReservoir`
                (the organism is an open system, fed by an environmental influx)
                and returned to the environment as dissipated heat.
    Load     -- metabolic load / heat generated by computation.  It cannot do
                work, it diffuses to neighbours and decays slowly; it is
                accumulated computational stress.
    Entropy  -- information entropy, *driven up by load*.  It degrades fidelity
                (retrieval, confidence calibration, planning depth, memory
                consolidation), which changes behaviour.

    energy -> work -> load -> entropy -> (fidelity) -> behaviour -> recovery

Two implementations share one interface so the substrate is swappable:

* :class:`ClassicMetabolism`        -- the old economics (energy regenerates from
  nowhere, no load, fidelity always 1).  This is the experimental *control*.
* :class:`ThermodynamicMetabolism`  -- the coupled three-field physics.

Conservation is exact and testable (see :meth:`ThermodynamicMetabolism` and
``Organism.metabolic_total``): for the thermodynamic substrate,
``d(reservoir + energy + load) = influx - dissipated``.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field

from core.energy import Action, EnergyBudget
from core.entropy import EntropyField


def _clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, value))


#: How "complex" each action is, on a [0, 1] reachability scale.  As metabolic
#: load shrinks a module's action *capacity*, the most complex actions drop out
#: of reach first (learn, then plan, then think, ... down to communicate).  This
#: is what lets load deform the *decision geometry* rather than only outcomes.
ACTION_COMPLEXITY: dict[Action, float] = {
    Action.COMMUNICATE: 0.15,
    Action.OBSERVE: 0.20,
    Action.MEMORY_LOOKUP: 0.35,
    Action.THINK: 0.40,
    Action.PLAN: 0.60,
    Action.CREATE_MEMORY: 0.70,
    Action.LEARN: 0.80,
}


@dataclass
class EnergyReservoir:
    """A shared pool of free energy.  Energy is conserved: it only enters via
    :meth:`replenish` (environmental influx) and leaves as dissipated heat; the
    reservoir merely stores and hands it to modules on demand."""

    level: float = 1400.0
    capacity: float = 1400.0
    influx: float = 14.0

    def replenish(self, dt: float = 1.0) -> float:
        """Add environmental free energy; return the amount actually added."""
        added = min(self.influx * dt, max(0.0, self.capacity - self.level))
        self.level += added
        return added

    def draw(self, amount: float) -> float:
        """Hand out up to ``amount`` of energy; return what was available."""
        got = min(max(0.0, amount), self.level)
        self.level -= got
        return got


class Metabolism(ABC):
    energy: EnergyBudget
    entropy: EntropyField
    load: float
    dissipated: float

    @abstractmethod
    def can_afford(self, action: Action, scale: float = 1.0) -> bool: ...

    @abstractmethod
    def do_work(self, action: Action, scale: float = 1.0) -> bool: ...

    @abstractmethod
    def recover(self, reservoir: EnergyReservoir | None, sleeping: bool,
                dt: float = 1.0) -> None: ...

    @abstractmethod
    def fidelity(self) -> float: ...

    @abstractmethod
    def regulate(self) -> None: ...

    def capacity(self) -> float:
        """Size of the reachable action manifold, in [0, 1] (1 = unconstrained)."""
        return 1.0

    def reachable(self, action: Action) -> bool:
        """Whether ``action`` is currently *reachable* (independent of energy)."""
        return ACTION_COMPLEXITY.get(action, 0.5) <= self.capacity()

    def receive_load(self, amount: float) -> None:  # diffusion in (no-op default)
        pass

    def report(self) -> dict[str, float]:
        return {"energy": self.energy.level, "entropy": self.entropy.level,
                "load": self.load, "fidelity": self.fidelity()}


@dataclass
class ClassicMetabolism(Metabolism):
    """The control substrate: pure economics, no physics."""

    energy: EnergyBudget
    entropy: EntropyField
    load: float = 0.0
    dissipated: float = 0.0

    def can_afford(self, action: Action, scale: float = 1.0) -> bool:
        return self.energy.can_afford(action, scale)

    def do_work(self, action: Action, scale: float = 1.0) -> bool:
        return self.energy.consume(action, scale)

    def recover(self, reservoir: EnergyReservoir | None, sleeping: bool,
                dt: float = 1.0) -> None:
        self.energy.regenerate(dt, multiplier=1.6 if sleeping else 1.0)

    def fidelity(self) -> float:
        return 1.0

    def regulate(self) -> None:
        self.entropy.relax()


@dataclass
class ThermodynamicMetabolism(Metabolism):
    """Three coupled fields: energy (conserved), load (heat), entropy (noise)."""

    energy: EnergyBudget
    entropy: EntropyField
    heat_fraction: float = 0.6      # share of work energy retained as load
    load_decay: float = 0.08        # slow dissipation of load per tick
    uptake: float = 6.0             # max energy drawn from reservoir per tick
    load_to_entropy: float = 0.6    # coupling: load -> information entropy
    fidelity_gain: float = 0.85     # how strongly entropy degrades fidelity
    action_ceiling: float = 0.9     # load (as frac. of capacity) that collapses actions
    load: float = 0.0
    dissipated: float = 0.0

    def can_afford(self, action: Action, scale: float = 1.0) -> bool:
        return self.energy.level >= self.energy.cost_of(action, scale)

    def do_work(self, action: Action, scale: float = 1.0) -> bool:
        cost = self.energy.cost_of(action, scale)
        if self.energy.level < cost:
            return False
        self.energy.spend(cost)
        # Work turns energy into heat: part is retained as load (stress), the
        # rest is dissipated immediately.  Both are accounted for (conservation).
        self.load += cost * self.heat_fraction
        self.dissipated += cost * (1.0 - self.heat_fraction)
        return True

    def recover(self, reservoir: EnergyReservoir | None, sleeping: bool,
                dt: float = 1.0) -> None:
        # 1. Draw free energy from the shared reservoir (a conserved transfer,
        #    bounded by the deficit so nothing is lost).
        deficit = self.energy.capacity - self.energy.level
        want = min(self.uptake * dt * (1.4 if sleeping else 1.0), deficit)
        if reservoir is not None:
            self.energy.level += reservoir.draw(want)
        else:  # no reservoir -> behave like an unlimited feed
            self.energy.level += want
        # 2. Dissipate load (cool down); sleeping cools ~3x faster.
        rate = self.load_decay * (3.0 if sleeping else 1.0)
        lost = self.load * _clamp(rate * dt)
        self.load -= lost
        self.dissipated += lost

    def fidelity(self) -> float:
        return _clamp(1.0 - self.fidelity_gain * self.entropy.level)

    def capacity(self) -> float:
        # As load rises toward the ceiling, the reachable action manifold
        # shrinks; at the ceiling only the cheapest acts (or none) remain.
        ceiling = self.action_ceiling * self.energy.capacity
        return _clamp(1.0 - self.load / ceiling) if ceiling > 0 else 0.0

    def regulate(self) -> None:
        # Metabolic load raises information entropy (normalised by capacity),
        # then entropy relaxes toward its baseline.
        pressure = self.load / max(1.0, self.energy.capacity)
        self.entropy.perturb(self.load_to_entropy * _clamp(pressure))
        self.entropy.relax()

    def receive_load(self, amount: float) -> None:
        self.load = max(0.0, self.load + amount)


def build_metabolism(mode: str, energy: EnergyBudget, entropy: EntropyField,
                     params: dict | None = None) -> Metabolism:
    """Factory: ``"classic"`` or ``"thermodynamic"`` (extra kwargs from params)."""
    if mode == "thermodynamic":
        p = params or {}
        return ThermodynamicMetabolism(
            energy, entropy,
            heat_fraction=p.get("heat_fraction", 0.6),
            load_decay=p.get("load_decay", 0.08),
            uptake=p.get("uptake", 6.0),
            load_to_entropy=p.get("load_to_entropy", 0.6),
            fidelity_gain=p.get("fidelity_gain", 0.85),
            action_ceiling=p.get("action_ceiling", 0.9))
    return ClassicMetabolism(energy, entropy)
